name: Build

on:
  push:
    branches: [ stage2 ]
  pull_request:
    branches: [ stage2 ]
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.3.0
      with:
        version: master

    - name: Test
      run: |
        zig build test

    - name: Fetch Vulkan SDK
      run: |
        wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.3.216-focal.list https://packages.lunarg.com/vulkan/1.3.216/lunarg-vulkan-1.3.216-focal.list
        sudo apt update
        sudo apt install shaderc libglfw3 libglfw3-dev

    - name: Fetch latest vk.xml
      run: |
        wget https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/main/xml/vk.xml

    - name: Build with latest zig & vk.xml
      run: |
        zig build -fno-stage1 -Dvulkan-registry=./vk.xml

    - name: Archive vk.xml
      uses: actions/upload-artifact@v2
      with:
        name: vk.zig
        path: zig-cache/vk.zig
